defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  signing_key: <%= ENV["SIGNING_KEY"] %>
  api_cps:
    username: <%= ENV['API_CPS_USERNAME'] %>
    password: <%= ENV['API_CPS_PASSWORD'] %>
    client_id: <%= ENV['API_CPS_CLIENT_ID'] %>
    client_secret: <%= ENV['API_CPS_CLIENT_SECRET'] %>
  mailjet:
    api_key: <%= ENV['MAILJET_API_KEY'] %>
    secret_key: <%= ENV['MAILJET_SECRET_KEY'] %>

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults

