name: 'Setup Rails app'
description: 'Setup the environment for running the Rails app'

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Update RubyGems
      run: gem update --system
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install Node modules
      run: |
        node --version
        bun --version
        bun install --frozen-lockfile
      shell: bash

    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://imd_test@localhost:5432/imd_test"
      run: bin/rails db:create db:schema:load db:migrate
      shell: bash
