name: 'Setup Rails assets'
description: 'Pre-compile and cache the app assets'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install JS dependencies
      run: bun install --frozen-lockfile
      shell: bash

    - name: Assets cache
      uses: actions/cache@v4
      with:
        path: |
          public/assets
          app/assets/builds
        key: asset-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          asset-cache-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          asset-cache-${{ runner.os }}-${{ github.ref }}-
          asset-cache-${{ runner.os }}-

    - name: Build CSS
      run: bun run build:css
      shell: bash

    - name: Precompile assets
      env:
        RAILS_ENV: test
      run: |
        bin/rails assets:precompile --trace
      shell: bash
